const fs = require('fs');
const path = require('path');
const { generateKeyPairSync } = require('crypto');

const DATA_DIR = path.join(__dirname, '../data');
const KEY_PATH = path.join(DATA_DIR, 'license-keys.json');

const ensureKeys = () => {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

  if (fs.existsSync(KEY_PATH)) {
    return JSON.parse(fs.readFileSync(KEY_PATH, 'utf8'));
  }

  const { privateKey, publicKey } = generateKeyPairSync('ec', {
    namedCurve: 'P-256',
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }
  });

  const keys = { privateKey, publicKey, createdAt: new Date().toISOString() };
  fs.writeFileSync(KEY_PATH, JSON.stringify(keys, null, 2));

  const envSnippet = path.join(DATA_DIR, 'mantis-env-snippet.txt');
  fs.writeFileSync(
    envSnippet,
    `# Add to your Mantis .env (generated by portal on first start)\nLICENSE_PUBLIC_KEY="${publicKey.replace(/\n/g, '\\n')}"\nPORTAL_URL=http://localhost:4000\n`
  );

  return keys;
};

module.exports = { ensureKeys, KEY_PATH };
